### ISSUE TITLE
When support nestjs version ^10.0.0 is gonna get released?

### ISSUE THREAD

**Issue by 4H1R** [nest-modules/mailer#997] opened 2023-06-22 09:45 UTC
Right now i'm trying to update the nest js to version 10 but it says mailer module doesn't support nest version 10 I can see that it's supported by when it's gonna get released on npm ?

**Comment by Shchepotin** [comment] 2023-06-22 11:45
@juandav could you please create new NPM build for apply these changes #995?

**Comment by adminha** [comment] 2023-06-24 06:41
please update the npm package, we're stuck ...

**Comment by ahmadalfy** [comment] 2023-06-25 16:59
If you are stuck you can replace it with `nodemailer`. Check [this](https://github.com/nest-modules/mailer/discussions/998).

**Comment by ramirosacruz** [comment] 2023-06-25 17:51
+1

**Comment by webgene** [comment] 2023-06-26 05:55
@juandav Please publish v1.8.2 to NPM. We are stuck.

**Comment by rnkdsh** [comment] 2023-06-26 07:54
+1

**Comment by wilsilva** [comment] 2023-06-26 19:38
+1

**Comment by bvedam** [comment] 2023-06-26 23:10
+1

**Comment by slavik-pastushenko** [comment] 2023-06-27 07:32
+1

**Comment by prakashchokalingam** [comment] 2023-06-27 10:55
+1 @juandav

**Comment by balenaultra** [comment] 2023-06-27 11:12
Judging by this PR https://github.com/nest-modules/mailer/pull/995, that only the dependencies was changed, I just installed the package with the `--force` and it worked for me
Can be an option for those that are stuck

**Comment by maticorv** [comment] 2023-06-28 13:14
+1

**Comment by TS-Tino16** [comment] 2023-06-28 17:28
+1 

For now I just used [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in my `package.json`, perhaps this helps someone:

```JSON
"overrides": {
    "@nestjs-modules/mailer": {
      "@nestjs/common": "$@nestjs/common",
      "@nestjs/core": "$@nestjs/core"
    }
}
```

**Comment by GeorgeHulpoi** [comment] 2023-06-29 08:40
+1 @juandav

**Comment by tmirun** [comment] 2023-06-30 08:44
+1

**Comment by bernatsc** [comment] 2023-06-30 08:45
+1

**Comment by saretoduncan** [comment] 2023-07-01 09:17
+1

**Comment by leo-belanger** [comment] 2023-07-05 12:56
Any news on this? It's been 2 weeks.

**Comment by Shchepotin** [comment] 2023-07-05 13:00
Looks like this repo is abandoned

**Comment by Shchepotin** [comment] 2023-07-05 13:03
@GeorgeHulpoi me too

**Comment by ggagosh** [comment] 2023-07-06 14:12
up 🚀

**Comment by carvalhomm** [comment] 2023-07-09 12:48
+1

**Comment by adevaraz** [comment] 2023-07-10 02:43
Is there any news?

**Comment by ggagosh** [comment] 2023-07-12 09:08
up 🤖

**Comment by alirezanqp** [comment] 2023-07-15 09:26
+

**Comment by broscr** [comment] 2023-07-17 06:19
+1

**Comment by ggagosh** [comment] 2023-07-17 08:39
UPUP

**Comment by JonathanLoscalzo** [comment] 2023-07-17 14:19
+100 :100: 

The workaround to execute --force works, but the issue is i don't want to force the installation

**Comment by v-angolenko** [comment] 2023-07-18 08:18
Can't upgrade to nest 1.10.X.

**Comment by juandav** [comment] 2023-07-20 02:07
The version 1.9.1 of the library has been released.

**Comment by dantehemerson** [comment] 2023-11-10 02:06
@juandav Since the lib support nest 10, can we close this issue?

**Closed** 2023-11-11 16:24 UTC
