### ISSUE TITLE
File can't be found, template path

### ISSUE THREAD

**Issue by Yevhen-Molchaniuk** [nest-modules/mailer#569] opened 2021-04-28 05:13 UTC
Hello guys, when my version of nest-modules/mailer was updated to lastest, the issue was appear,
In the handlebarsAdapter some code was changed as i can see and know their exists this condition 
[link to code](https://github.com/nest-modules/mailer/blob/1df331559aced871d18354d7ad6f976ee6aa6496/lib/adapters/handlebars.adapter.ts#L38)
```
const templateDir = template.startsWith('./')
? lodash_1.get(options, 'dir', '')
: path.dirname(template);
```
which cause many issues in my project, but documentation wasn't changed, please fix the documentation 
All templates which are using handlebars should be defined with **./welcome** because in another case file directory will be used
![image](https://user-images.githubusercontent.com/81360603/116350111-0c013380-a7fa-11eb-9969-5c7b6d58979e.png)

**Comment by hddananjaya** [comment] 2021-04-28 08:15
@Yevhen-Molchaniuk Did you get the same error as this? #570

**Comment by Yevhen-Molchaniuk** [comment] 2021-04-28 08:22
No, My issue in that i didn't use './' in template option, but if i will use it, all will be fine, please add this information to documentation

**Comment by hddananjaya** [comment] 2021-04-28 08:42
> No, My issue in that i didn't use './' in template option, but if i will use it, all will be fine, please add this information to documentation

Thanks for this. It solved my problem as well. (#570)

**Comment by 1ur11** [comment] 2021-05-06 14:40
Have similar issue.
change template name to './' helps.

**Comment by GerkinDev** [comment] 2021-06-18 15:10
Duplicate of #494

**Closed** 2023-12-22 18:44 UTC
